// This file is generated by `npm run generate:ipc-types`.
// Do not edit it by hand. Change the Rust DTO and regenerate instead.

export type BackendKind = "matrix" | "legacy-p2p";

export type VoiceProvider = "matrix-rtc" | "legacy-simple-peer";

export type VoiceServiceAvailability = "ready" | "not-configured" | "invalid-configuration" | "client-unavailable";

export type VoiceServiceStatus = { provider: VoiceProvider, availability: VoiceServiceAvailability, discoveryKey: string | null, livekitServiceUrl: string | null, tokenEndpoint: string | null, livekitSfuUrl: string | null, cspReady: boolean,
/**
 * The selected build contains the media-encryption client and its
 * required network policy. Live media verification is a release gate.
 */
mediaE2eeReady: boolean, reason: string | null, };

export type BackendCapabilities = { encryptedText: boolean, encryptedAttachments: boolean, directMessages: boolean, voice: boolean, durableTimeouts: boolean, deviceManagement: boolean, recovery: boolean, legacyMigration: boolean, };

export type BackendStartupPhase = "pending" | "starting" | "ready" | "recoverable-failure";

export type BackendStartupIssue = "sign-in-required" | "connection-unavailable" | "service-unavailable" | "runtime-unavailable";

export type BackendStartupStatus = { phase: BackendStartupPhase, issue: BackendStartupIssue | null, };

export type BackendStatus = { kind: BackendKind, capabilities: BackendCapabilities, voiceService: VoiceServiceStatus, authenticated: boolean, userId: string | null, deviceId: string | null, homeserver: string | null,
/**
 * True only when the sync worker is alive and has received a successful
 * response within the backend's freshness window.
 */
syncRunning: boolean, durableHistory: boolean,
/**
 * Backend capability. This does not claim that the current account has a
 * usable authenticated encryption session.
 */
supportsE2ee: boolean,
/**
 * Health of the current account/device encryption session.
 */
sessionE2eeReady: boolean, warnings: Array<string>, };

export type MatrixPersonalDataExport = { path: string, exportedAt: string, roomCount: number, messageCount: number, mediaFileCount: number, warnings: Array<string>, };

export type MatrixNotification = { roomId: string, eventId: string, sender: string, displayName: string, preview: string, isMention: boolean, isDm: boolean,
/**
 * The sender's picture, as the backend read it, and always absent by the
 * time anything outside the backend sees this.
 *
 * `presentation_notification` clears it before both the renderer event and
 * the native notification, whatever the content policy says, because
 * nothing presents it: the renderer only plays a sound for a notification,
 * and a native notification image is a per-platform capability rather than
 * something Mesh can show the same way on Windows, macOS and Linux. The
 * field stays because that clearing is a privacy guarantee worth pinning a
 * test to, and the tests need something to assert about.
 */
avatarUrl: string | null, };

export type MatrixNotificationActivation = { roomId: string, eventId: string, isDm: boolean, };

export type MatrixUnreadUpdate = { roomId: string, unreadMessages: number, unreadMentions: number,
/**
 * Whether this room carries the person's own explicit "mark as unread"
 * marker (`m.marked_unread` room account data), independent of whether
 * any message or mention is actually unread.
 */
unreadMarked: boolean, };

export type MatrixTypingChanged = { roomId: string, };

export type MatrixIgnoredUsersChanged = {
/**
 * Newly ignored accounts that can be removed from bounded renderer caches
 * without discarding unrelated conversations.
 */
blockedUserIds: Array<string>,
/**
 * The change was too large or the previous account state was unknown, so
 * renderer message projections must be cleared and loaded again.
 */
resetAll: boolean, };

export type MatrixPermissionRoomStatus = "loaded" | "matrix-default" | "inaccessible" | "unsupported" | "failed";

export type CommunityPermissionAggregateStatus = "granted-everywhere" | "granted-some-rooms" | "not-granted" | "unknown";

export type CommunityPermissionId = "participate" | "invite" | "redact" | "remove" | "ban" | "roomState" | "roles";

export type MatrixRoomPowerLevelProjection = { users: { [key in string]?: number }, usersDefault: number, events: { [key in string]?: number }, eventsDefault: number, stateDefault: number, ban: number, kick: number, invite: number, redact: number, notifications: { [key in string]?: number }, creatorUserIds: Array<string>, privilegedCreatorUserIds: Array<string>, };

export type MatrixRoomPermissionProjection = { roomId: string, roomName: string, roomKind: "space" | "room", status: MatrixPermissionRoomStatus, policy: MatrixRoomPowerLevelProjection | null, failureReason: string | null, };

export type CommunityPermissionAggregate = { permissionId: CommunityPermissionId, status: CommunityPermissionAggregateStatus, grantedRoomCount: number, verifiedRoomCount: number, totalRoomCount: number, };

export type CommunityPermissionProjection = { communityId: string, subjectUserId: string, discoveryComplete: boolean, discoveryFailureReason: string | null, rooms: Array<MatrixRoomPermissionProjection>, aggregate: Array<CommunityPermissionAggregate>, };

export type MatrixPermissionStateChanged = { roomId: string, };

export type MatrixRoomUpdateKind = "idle" | "timeline" | "state" | "ephemeral";

export type MatrixQueuedMessageState = "pending" | "failed" | "sent" | "cancelled";

export type MatrixQueuedMessageFailure = "not-allowed" | "room-unavailable" | "unknown";

export type MatrixQueuedMessageUpdate = { roomId: string, transactionId: string, state: MatrixQueuedMessageState, eventId?: string | null, message?: MessageDto | null,
/**
 * Set only when `state` is `Failed`. A failure the renderer can explain is
 * the difference between "your connection dropped, try again" and "you are
 * not allowed to post here", which no amount of retrying will change.
 */
failure?: MatrixQueuedMessageFailure | null, };

export type MatrixRoomNotificationMode = "all" | "mentions" | "nothing";

export type MatrixRoomUpgrade = { roomId: string, replacementRoomId: string | null, predecessorRoomId: string | null, reason: string | null, };

export type MatrixRoomPins = { roomId: string, eventIds: Array<string>, messages: Array<MessageDto>, unavailableEventIds: Array<string>, canManage: boolean, };

export type MatrixRoomPinsUpdate = { roomId: string, eventIds: Array<string>, };

export type MatrixTransferDirection = "upload" | "download";

export type MatrixTransferState = "queued" | "encrypting" | "uploading" | "publishing" | "downloading" | "validating" | "writing" | "completed" | "cancelled" | "failed";

export type MatrixTransferRetryMode = "restart-from-zero";

export type MatrixTransferResult = { eventId: string | null, localPath: string | null, };

export type MatrixTransferProgress = { transferId: string, direction: MatrixTransferDirection, transferredBytes: number, totalBytes: number | null, state: MatrixTransferState, retryable: boolean, retryMode: MatrixTransferRetryMode | null, result: MatrixTransferResult | null, error: string | null, };

export type MatrixRtcMember = { roomId: string, userId: string, deviceId: string, sessionId: string, displayName: string, avatarUrl: string | null,
/**
 * What this member is called inside the call itself.
 *
 * The SFU never learns a Matrix user ID: a participant is identified by a
 * digest of user, device and membership, so nothing in the renderer can
 * tell which LiveKit participant is which person from the participant list
 * alone. Sending the same digest with the membership is what lets a call
 * tile show a name and a picture. Derived exactly as
 * `MatrixRtcMediaKey::participant_identity` is, which is the derivation
 * end-to-end encrypted media already depends on matching.
 */
participantIdentity: string, };

export type MatrixRtcMembershipUpdate = { roomId: string, members: Array<MatrixRtcMember>, };

export type MatrixRtcMediaKey = { roomId: string, userId: string, deviceId: string, memberId: string, sessionId: string | null, activationId: string | null, participantIdentity: string, keyIndex: number, key: string, sentTs: number, };

export type MatrixRtcMediaKeyFailure = { roomId: string, code: string, };

export type MatrixRtcMediaKeyPause = { roomId: string, sessionId: string, memberId: string, activationId: string, keyIndex: number, };

export type MatrixRtcMediaKeyLease = { roomId: string, sessionId: string, memberId: string, keyIndex: number, expiresAt: number, };

export type MatrixRtcJoinResult = { roomId: string, sessionId: string, memberId: string, url: string, token: string, roomName: string, participantIdentity: string,
/**
 * The client has the media-encryption worker and key material needed to
 * attempt a protected call. This is not proof of a successful live call.
 */
mediaE2eeReady: boolean, mediaKey: MatrixRtcMediaKey, };

export type NotificationPresentationContext = { activeRoomId: string | null, notificationsEnabled: boolean, doNotDisturb: boolean, quietHoursActive: boolean,
/**
 * Explicit account-scoped opt-in for showing bounded message text in
 * native notifications. Missing values fail closed for older clients.
 */
showMessageContent: boolean, mutedRoomIds: Array<string>, };

export type MatrixRecoverySecureStorageState = "saved" | "missing" | "unavailable";

export type MatrixRecoveryVerificationState = "verified" | "failed";

export type MatrixRecoveryHealth = { recoveryState: string, backupState: string, backupExistsOnServer: boolean, backupEnabled: boolean, healthy: boolean, checkedAt: string, lastSuccessfulTestAt: string | null, secureStorageState: MatrixRecoverySecureStorageState, warnings: Array<string>, };

export type MatrixRecoverySetupResult = { recoveryKey: string, secureStorageState: MatrixRecoverySecureStorageState, verificationState: MatrixRecoveryVerificationState, };

export type ReadReceiptMode = "public" | "private" | "off";

export type ConversationPrivacyOverride = { readReceiptMode?: ReadReceiptMode | null, sendTypingIndicators?: boolean | null, };

export type UserPreferences = { schemaVersion: number, notificationsEnabled: boolean, notificationSound: boolean, notificationSoundId?: string | null, interfaceSoundVolume: number, interfaceSoundEvents: { [key in string]?: boolean }, doNotDisturb: boolean,
/**
 * Whether bounded message text may appear in native notifications.
 * Fresh and migrated accounts remain private unless the user opts in.
 */
showNotificationContent: boolean, quietHoursEnabled: boolean, quietHoursStart?: string | null, quietHoursEnd?: string | null, mutedChannels: Array<string>, mutedCommunities: Array<string>, mutedChannelUntil: { [key in string]?: string | null }, mutedCommunityUntil: { [key in string]?: string | null }, channelNotificationLevels: { [key in string]?: MatrixRoomNotificationMode }, sendReadReceipts: boolean,
/**
 * Explicit receipt visibility. Missing values are migrated from the
 * legacy boolean: true meant private-only and false meant off.
 */
readReceiptMode?: ReadReceiptMode | null, sendTypingIndicators: boolean,
/**
 * Optional per-conversation privacy choices, keyed by Matrix room ID.
 * Missing fields inherit the account-level choice above.
 */
conversationPrivacy: { [key in string]?: ConversationPrivacyOverride }, sharePresence: boolean, invisibleMode: boolean, updatedAt: string, };

export type CustomEmoji = { shortcode: string, body: string, mxcUri: string, contentType: string, width: number, height: number, sizeBytes: number, };

export type ModerationRoomOutcome = { roomId: string, roomName: string, succeeded: boolean, failureReason: string | null, };

export type ModerationAuditEntry = { id: string, actorUserId: string, actorDisplayName: string, targetUserId: string, targetDisplayName: string, action: string, reason: string | null, occurredAt: string, roomOutcomes: Array<ModerationRoomOutcome>, };

export type CommunityModerationResult = { audit: ModerationAuditEntry, auditRecorded: boolean,
/**
 * Why no durable record was written, when none was.
 *
 * `audit_recorded: false` on its own reads as "Mesh tried and failed",
 * and today it always means "Mesh declines to treat a forgeable room
 * message as evidence" -- a policy, not a fault. Once a real audit store
 * exists those two become genuinely different outcomes, and a bare
 * boolean could not tell them apart.
 */
auditUnrecordedReason?: string | null, };

export type MatrixCommunityAdmission = { roomId: string, service: string, via: Array<string>, expiresAt?: number | null, communityName?: string | null, inviterDisplayName?: string | null, inviterUserId?: string | null, joinRule?: string | null, communityServiceDisplayName?: string | null, };

export type PendingInvitationMetadata = { handle: string, roomOrAlias: string | null, via: Array<string>, service: string | null, admissionService: string | null, communityName?: string | null, inviterDisplayName?: string | null, inviterUserId?: string | null, joinRule?: string | null, communityServiceDisplayName?: string | null, storedAt: number, expiresAt: number, };

export type IdentityDto = { publicKey: string, displayName: string, avatarColor: string, };

export type CommunityDto = { id: string, name: string, description: string,
/**
 * This community's icon as an MXC URI, or `None` when it has none and the
 * generated mark stands in. The renderer cannot fetch an MXC URI, so it
 * resolves this through `matrix_load_profile_avatar` rather than putting it
 * in an `img` element; `Avatar` does that on its behalf.
 */
avatarUrl: string | null, memberCount: number, role: "owner" | "admin" | "member", joinedAt: string | null, };

export type CommunityInviteDto = { roomId: string, name: string, inviterUserId: string, inviterDisplayName: string, inviterAvatarColor: string,
/**
 * False when the space is not end-to-end encrypted. Mesh requires
 * encryption before it will join, so the invitation can only be declined.
 */
canAccept: boolean, };

export type ChannelDto = { id: string, communityId: string, name: string,
/**
 * What this room is for, from the standard `m.room.topic` state event.
 * Empty when the room has none, matching `CommunityDto::description`, which
 * surfaces the same Matrix field for a space.
 */
topic: string, channelType: "text" | "voice", unreadCount: number,
/**
 * Whether this account is a member of the room, as opposed to a room it is
 * allowed to join and has not.
 *
 * A community's rooms are created so that any member of the community may
 * join them, but nothing joins an existing member to a room created after
 * they arrived. Those rooms used to be dropped from this listing and
 * reported as unopenable, which described a permission problem that did not
 * exist. They are listed here instead, and `false` is the whole reason a
 * caller must offer to join rather than open: no timeline, no unread count,
 * and no read receipt is available for a room this account is not in.
 *
 * A room this account joined and later left reads the same as one it was
 * never in, and that is deliberate. Both are rooms the community still
 * lists and still admits this account to, so both can be rejoined on the
 * same terms; before this they were both reported as rooms Mesh could not
 * open. Somebody who does not want to see one again hides the row, which is
 * local and does not need a membership to express.
 */
joined: boolean, };

export type AttachmentThumbnailDto = { fileHash: string, size: number, width: number, height: number, contentType: string, };

export type AttachmentDto = { fileHash: string, filename: string, size: number, chunks: number, sourcePeerId: string, contentType?: string | null,
/**
 * Bounded display metadata for a protected inline preview. Encryption
 * keys, IVs, and media locations remain Rust-only.
 */
thumbnail?: AttachmentThumbnailDto | null, };

export type UndecryptableMessageReason = "sent-before-device" | "keys-not-shared" | "waiting-for-keys" | "could-not-decrypt";

export type UndecryptableMessageDto = { eventId: string, sender: string, originServerTs: number, reason: UndecryptableMessageReason, };

export type ComposerDraftDto = { body: string, formattedBody?: string | null, };

export type MessageDto = { id: string, channelId: string, authorPublicKey: string, authorDisplayName: string, authorAvatarColor: string,
/**
 * The author's profile picture as an `mxc://` URI, when they have one.
 *
 * Read from the room's member state as the message is projected rather
 * than stored alongside it, exactly like `author_display_name`, so
 * replacing or clearing a picture takes effect everywhere at once instead
 * of leaving the old address on old messages. `author_avatar_color` stays
 * the fallback and is always present.
 *
 * The renderer cannot put this in an `img` element: the content security
 * policy allows no `mxc://` and the media endpoint needs the access token.
 * `Avatar` resolves it through `matrix_load_profile_avatar`.
 */
authorAvatarUrl?: string | null, content: string,
/**
 * Explicit notification recipients carried by the standard m.mentions field.
 */
mentions?: Array<string>,
/**
 * Whether this message notified the whole room, from the standard
 * `m.mentions.room` flag.
 *
 * This is per-message and not a room capability, which is the whole point:
 * only the sender's power level at the time of sending decides whether a
 * room-wide mention took effect, so a member who lacks it and writes
 * `@room` anyway produces a message where this is `false`. The renderer
 * highlights the token only when this is set, so what a reader sees agrees
 * with who was actually notified rather than with what was typed.
 */
mentionsRoom?: boolean, attachments: Array<AttachmentDto>, reactions: Record<string, string[]>, timestamp: string, signature: string, editedAt?: string | null, deletedAt?: string | null, replyToId?: string | null,
/**
 * Matrix thread root event for replies sent with `rel_type: m.thread`.
 * Ordinary replies leave this empty and continue using `reply_to_id`.
 */
threadRootId?: string | null,
/**
 * SDK transaction ID used to reconcile a durable local echo with the
 * eventual server event. This is internal delivery metadata.
 */
transactionId?: string | null,
/**
 * Renderer request ID retained inside the encrypted event so a lost IPC
 * response can be retried without publishing a duplicate.
 */
clientRequestId?: string | null,
/**
 * Delivery status: "sent", "pending", or "failed". None = sent.
 */
deliveryStatus?: "sent" | "pending" | "failed" | null,
/**
 * Present only when Matrix received an event but the SDK could not
 * decrypt its message content.
 */
undecryptable?: UndecryptableMessageDto | null, };

export type MatrixThreadContextDto = { root: MessageDto, replies: Array<MessageDto>, unreadCount: number, unreadMentions: number, unreadStateAvailable: boolean, hasMore: boolean, };

export type ThreadListItemDto = { root: MessageDto, replyCount: number, participantCount: number, lastActivity: string, unreadCount: number, unreadMentions: number, };

export type MatrixThreadListDto = { items: Array<ThreadListItemDto>, hasMore: boolean, };

export type MatrixSearchScopeDto = { communitiesSearched: number, communitiesTotal: number, roomsSearched: number, roomsTotal: number, truncated: boolean, };

export type MatrixCrossCommunitySearchResultDto = { results: Array<MessageDto>, scope: MatrixSearchScopeDto, };

export type DmPeerDto = { userId: string, displayName: string, avatarColor: string,
/**
 * The peer's profile picture as an `mxc://` URI, when they have one, read
 * from the direct room's member state beside their display name.
 * `avatar_color` stays the fallback and is always present. The renderer
 * resolves this through `matrix_load_profile_avatar`; see `MessageDto`.
 */
avatarUrl?: string | null, };

export type DmConversationDto = { id: string,
/**
 * The other participants, never empty. Exactly one for a one-to-one DM.
 */
peers: Array<DmPeerDto>, lastMessageAt: string | null, unreadCount: number, createdAt: string, };

export type DmRequestDto = { roomId: string, inviterUserId: string, inviterDisplayName: string, inviterAvatarColor: string, canAccept: boolean, };

export type BlockedAccountDto = { userId: string, };

export type BlockedAccountPageDto = { accounts: Array<BlockedAccountDto>, nextCursor: string | null, };

export type ReadReceiptDto = { userId: string, displayName: string, };

export type DirectMessageDto = { id: string, conversationId: string, authorPublicKey: string, authorDisplayName: string, authorAvatarColor: string,
/**
 * The author's profile picture, on the same terms as `MessageDto`: read
 * from member state when the message is projected, never stored with it.
 */
authorAvatarUrl?: string | null, content: string, timestamp: string, signature: string, attachments: Array<AttachmentDto>, reactions: Record<string, string[]>, seenBy?: Array<ReadReceiptDto> | null, editedAt?: string | null, deletedAt?: string | null, replyToId?: string | null, threadRootId?: string | null, deliveryStatus?: "sent" | "pending" | "failed" | null, };

export type PeerDto = { publicKey: string, displayName: string, avatarColor: string, peerId: string, latency: number, };

export type NetworkStatusDto = { connected: boolean, peerCount: number, averageLatency: number, usingRelay: boolean, };
