// This file is generated by `npm run generate:ipc-types`.
// Do not edit it by hand. Change the Rust DTO and regenerate instead.

export type BackendKind = "matrix" | "legacy-p2p";

export type VoiceProvider = "matrix-rtc" | "legacy-simple-peer";

export type VoiceServiceAvailability = "ready" | "not-configured" | "invalid-configuration" | "client-unavailable";

export type VoiceServiceStatus = { provider: VoiceProvider, availability: VoiceServiceAvailability, discoveryKey: string | null, livekitServiceUrl: string | null, tokenEndpoint: string | null, livekitSfuUrl: string | null, cspReady: boolean, mediaE2eeVerified: boolean, reason: string | null, };

export type BackendCapabilities = { encryptedText: boolean, encryptedAttachments: boolean, directMessages: boolean, voice: boolean, durableTimeouts: boolean, deviceManagement: boolean, recovery: boolean, legacyMigration: boolean, };

export type BackendStatus = { kind: BackendKind, capabilities: BackendCapabilities, voiceService: VoiceServiceStatus, authenticated: boolean, userId: string | null, deviceId: string | null, homeserver: string | null, syncRunning: boolean, durableHistory: boolean, endToEndEncryption: boolean, warnings: Array<string>, };

export type MatrixNotification = { roomId: string, eventId: string, sender: string, displayName: string, preview: string, isMention: boolean, isDm: boolean, avatarUrl: string | null, };

export type MatrixUnreadUpdate = { roomId: string, unreadMessages: number, unreadMentions: number, };

export type MatrixRoomNotificationMode = "all" | "mentions" | "nothing";

export type MatrixRtcMember = { roomId: string, userId: string, deviceId: string, sessionId: string, displayName: string, avatarUrl: string | null, };

export type MatrixRtcMembershipUpdate = { roomId: string, members: Array<MatrixRtcMember>, };

export type MatrixRtcMediaKey = { roomId: string, userId: string, deviceId: string, memberId: string, sessionId: string | null, activationId: string | null, participantIdentity: string, keyIndex: number, key: string, sentTs: number, };

export type MatrixRtcMediaKeyFailure = { roomId: string, code: string, };

export type MatrixRtcMediaKeyPause = { roomId: string, sessionId: string, memberId: string, activationId: string, keyIndex: number, };

export type MatrixRtcMediaKeyLease = { roomId: string, sessionId: string, memberId: string, keyIndex: number, expiresAt: number, };

export type MatrixRtcJoinResult = { roomId: string, sessionId: string, memberId: string, url: string, token: string, roomName: string, participantIdentity: string, mediaE2eeVerified: boolean, mediaKey: MatrixRtcMediaKey, };

export type NotificationPresentationContext = { activeRoomId: string | null, notificationsEnabled: boolean, doNotDisturb: boolean, quietHoursActive: boolean, mutedRoomIds: Array<string>, };

export type UserPreferences = { schemaVersion: number, notificationsEnabled: boolean, notificationSound: boolean, notificationSoundId?: string | null, doNotDisturb: boolean, quietHoursEnabled: boolean, quietHoursStart?: string | null, quietHoursEnd?: string | null, mutedChannels: Array<string>, mutedCommunities: Array<string>, mutedChannelUntil: { [key in string]?: string | null }, mutedCommunityUntil: { [key in string]?: string | null }, channelNotificationLevels: { [key in string]?: MatrixRoomNotificationMode }, sendReadReceipts: boolean, sendTypingIndicators: boolean, sharePresence: boolean, invisibleMode: boolean, updatedAt: string, };

export type IdentityDto = { publicKey: string, displayName: string, avatarColor: string, };

export type CommunityDto = { id: string, name: string, description: string, memberCount: number, role: "owner" | "admin" | "member", joinedAt: string | null, };

export type ChannelDto = { id: string, communityId: string, name: string, channelType: "text" | "voice", unreadCount: number, };

export type AttachmentThumbnailDto = { fileHash: string, size: number, width: number, height: number, contentType: string,
/**
 * Opaque Matrix encrypted-file metadata used only by the Rust backend.
 */
mediaSource: Record<string, unknown>, };

export type AttachmentDto = { fileHash: string, filename: string, size: number, chunks: number, sourcePeerId: string,
/**
 * Matrix encrypted-file metadata. Kept opaque at the product boundary so
 * the SDK remains the authority for key, IV, and ciphertext validation.
 */
mediaSource?: Record<string, unknown> | null, contentType?: string | null,
/**
 * Encrypted Matrix thumbnail metadata. Mesh does not decrypt this across
 * renderer IPC until the sandboxed preview boundary is implemented.
 */
thumbnail?: AttachmentThumbnailDto | null, };

export type MessageDto = { id: string, channelId: string, authorPublicKey: string, authorDisplayName: string, authorAvatarColor: string, content: string, attachments: Array<AttachmentDto>, reactions: Record<string, string[]>, timestamp: string, signature: string, editedAt?: string | null, deletedAt?: string | null, replyToId?: string | null,
/**
 * Delivery status: "sent", "pending", or "failed". None = sent.
 */
deliveryStatus?: "sent" | "pending" | "failed" | null, };

export type DmConversationDto = { id: string, peerPublicKey: string, peerDisplayName: string, peerAvatarColor: string, lastMessageAt: string | null, unreadCount: number, createdAt: string, };

export type DirectMessageDto = { id: string, conversationId: string, authorPublicKey: string, authorDisplayName: string, authorAvatarColor: string, content: string, timestamp: string, signature: string, attachments: Array<AttachmentDto>, reactions: Record<string, string[]>, editedAt?: string | null, deletedAt?: string | null, replyToId?: string | null, deliveryStatus?: "sent" | "pending" | "failed" | null, };

export type PeerDto = { publicKey: string, displayName: string, avatarColor: string, peerId: string, latency: number, };

export type NetworkStatusDto = { connected: boolean, peerCount: number, averageLatency: number, usingRelay: boolean, };
