// This file is generated by `npm run generate:ipc-types`.
// Do not edit it by hand. Change the Rust DTO and regenerate instead.

export type BackendKind = "matrix" | "legacy-p2p";

export type VoiceProvider = "matrix-rtc" | "legacy-simple-peer";

export type VoiceServiceAvailability = "ready" | "not-configured" | "invalid-configuration" | "client-unavailable";

export type VoiceServiceStatus = { provider: VoiceProvider, availability: VoiceServiceAvailability, discoveryKey: string | null, livekitServiceUrl: string | null, tokenEndpoint: string | null, livekitSfuUrl: string | null, cspReady: boolean,
/**
 * The selected build contains the media-encryption client and its
 * required network policy. Live media verification is a release gate.
 */
mediaE2eeReady: boolean, reason: string | null, };

export type BackendCapabilities = { encryptedText: boolean, encryptedAttachments: boolean, directMessages: boolean, voice: boolean, durableTimeouts: boolean, deviceManagement: boolean, recovery: boolean, legacyMigration: boolean, };

export type BackendStatus = { kind: BackendKind, capabilities: BackendCapabilities, voiceService: VoiceServiceStatus, authenticated: boolean, userId: string | null, deviceId: string | null, homeserver: string | null,
/**
 * True only when the sync worker is alive and has received a successful
 * response within the backend's freshness window.
 */
syncRunning: boolean, durableHistory: boolean,
/**
 * Backend capability. This does not claim that the current account has a
 * usable authenticated encryption session.
 */
supportsE2ee: boolean,
/**
 * Health of the current account/device encryption session.
 */
sessionE2eeReady: boolean, warnings: Array<string>, };

export type MatrixPersonalDataExport = { path: string, exportedAt: string, roomCount: number, messageCount: number, mediaFileCount: number, warnings: Array<string>, };

export type MatrixNotification = { roomId: string, eventId: string, sender: string, displayName: string, preview: string, isMention: boolean, isDm: boolean, avatarUrl: string | null, };

export type MatrixUnreadUpdate = { roomId: string, unreadMessages: number, unreadMentions: number, };

export type MatrixIgnoredUsersChanged = {
/**
 * Newly ignored accounts that can be removed from bounded renderer caches
 * without discarding unrelated conversations.
 */
blockedUserIds: Array<string>,
/**
 * The change was too large or the previous account state was unknown, so
 * renderer message projections must be cleared and loaded again.
 */
resetAll: boolean, };

export type MatrixPermissionRoomStatus = "loaded" | "matrix-default" | "inaccessible" | "unsupported" | "failed";

export type CommunityPermissionAggregateStatus = "granted-everywhere" | "granted-some-rooms" | "not-granted" | "unknown";

export type CommunityPermissionId = "participate" | "invite" | "redact" | "remove" | "ban" | "roomState" | "roles";

export type MatrixRoomPowerLevelProjection = { users: { [key in string]?: number }, usersDefault: number, events: { [key in string]?: number }, eventsDefault: number, stateDefault: number, ban: number, kick: number, invite: number, redact: number, notifications: { [key in string]?: number }, creatorUserIds: Array<string>, privilegedCreatorUserIds: Array<string>, };

export type MatrixRoomPermissionProjection = { roomId: string, roomName: string, roomKind: "space" | "room", status: MatrixPermissionRoomStatus, policy: MatrixRoomPowerLevelProjection | null, failureReason: string | null, };

export type CommunityPermissionAggregate = { permissionId: CommunityPermissionId, status: CommunityPermissionAggregateStatus, grantedRoomCount: number, verifiedRoomCount: number, totalRoomCount: number, };

export type CommunityPermissionProjection = { communityId: string, subjectUserId: string, discoveryComplete: boolean, discoveryFailureReason: string | null, rooms: Array<MatrixRoomPermissionProjection>, aggregate: Array<CommunityPermissionAggregate>, };

export type MatrixPermissionStateChanged = { roomId: string, };

export type MatrixQueuedMessageState = "pending" | "failed" | "sent" | "cancelled";

export type MatrixQueuedMessageUpdate = { roomId: string, transactionId: string, state: MatrixQueuedMessageState, eventId?: string | null, message?: MessageDto | null, };

export type MatrixRoomNotificationMode = "all" | "mentions" | "nothing";

export type MatrixRoomUpgrade = { roomId: string, replacementRoomId: string | null, predecessorRoomId: string | null, reason: string | null, };

export type MatrixRoomPins = { roomId: string, eventIds: Array<string>, messages: Array<MessageDto>, unavailableEventIds: Array<string>, canManage: boolean, };

export type MatrixRoomPinsUpdate = { roomId: string, eventIds: Array<string>, };

export type MatrixRtcMember = { roomId: string, userId: string, deviceId: string, sessionId: string, displayName: string, avatarUrl: string | null, };

export type MatrixRtcMembershipUpdate = { roomId: string, members: Array<MatrixRtcMember>, };

export type MatrixRtcMediaKey = { roomId: string, userId: string, deviceId: string, memberId: string, sessionId: string | null, activationId: string | null, participantIdentity: string, keyIndex: number, key: string, sentTs: number, };

export type MatrixRtcMediaKeyFailure = { roomId: string, code: string, };

export type MatrixRtcMediaKeyPause = { roomId: string, sessionId: string, memberId: string, activationId: string, keyIndex: number, };

export type MatrixRtcMediaKeyLease = { roomId: string, sessionId: string, memberId: string, keyIndex: number, expiresAt: number, };

export type MatrixRtcJoinResult = { roomId: string, sessionId: string, memberId: string, url: string, token: string, roomName: string, participantIdentity: string,
/**
 * The client has the media-encryption worker and key material needed to
 * attempt a protected call. This is not proof of a successful live call.
 */
mediaE2eeReady: boolean, mediaKey: MatrixRtcMediaKey, };

export type NotificationPresentationContext = { activeRoomId: string | null, notificationsEnabled: boolean, doNotDisturb: boolean, quietHoursActive: boolean,
/**
 * Explicit account-scoped opt-in for showing bounded message text in
 * native notifications. Missing values fail closed for older clients.
 */
showMessageContent: boolean, mutedRoomIds: Array<string>, };

export type MatrixRecoverySecureStorageState = "saved" | "missing" | "unavailable";

export type MatrixRecoveryVerificationState = "verified" | "failed";

export type MatrixRecoveryHealth = { recoveryState: string, backupState: string, backupExistsOnServer: boolean, backupEnabled: boolean, healthy: boolean, checkedAt: string, lastSuccessfulTestAt: string | null, secureStorageState: MatrixRecoverySecureStorageState, warnings: Array<string>, };

export type MatrixRecoverySetupResult = { recoveryKey: string, secureStorageState: MatrixRecoverySecureStorageState, verificationState: MatrixRecoveryVerificationState, };

export type ReadReceiptMode = "public" | "private" | "off";

export type ConversationPrivacyOverride = { readReceiptMode?: ReadReceiptMode | null, sendTypingIndicators?: boolean | null, };

export type UserPreferences = { schemaVersion: number, notificationsEnabled: boolean, notificationSound: boolean, notificationSoundId?: string | null, interfaceSoundVolume: number, interfaceSoundEvents: { [key in string]?: boolean }, doNotDisturb: boolean,
/**
 * Whether bounded message text may appear in native notifications.
 * Fresh and migrated accounts remain private unless the user opts in.
 */
showNotificationContent: boolean, quietHoursEnabled: boolean, quietHoursStart?: string | null, quietHoursEnd?: string | null, mutedChannels: Array<string>, mutedCommunities: Array<string>, mutedChannelUntil: { [key in string]?: string | null }, mutedCommunityUntil: { [key in string]?: string | null }, channelNotificationLevels: { [key in string]?: MatrixRoomNotificationMode }, sendReadReceipts: boolean,
/**
 * Explicit receipt visibility. Missing values are migrated from the
 * legacy boolean: true meant private-only and false meant off.
 */
readReceiptMode?: ReadReceiptMode | null, sendTypingIndicators: boolean,
/**
 * Optional per-conversation privacy choices, keyed by Matrix room ID.
 * Missing fields inherit the account-level choice above.
 */
conversationPrivacy: { [key in string]?: ConversationPrivacyOverride }, sharePresence: boolean, invisibleMode: boolean, updatedAt: string, };

export type CustomEmoji = { shortcode: string, body: string, mxcUri: string, contentType: string, width: number, height: number, sizeBytes: number, };

export type ModerationRoomOutcome = { roomId: string, roomName: string, succeeded: boolean, failureReason: string | null, };

export type ModerationAuditEntry = { id: string, actorUserId: string, actorDisplayName: string, targetUserId: string, targetDisplayName: string, action: string, reason: string | null, occurredAt: string, roomOutcomes: Array<ModerationRoomOutcome>, };

export type CommunityModerationResult = { audit: ModerationAuditEntry, auditRecorded: boolean, };

export type MatrixCommunityAdmission = { roomId: string, service: string, via: Array<string>, expiresAt?: number | null, communityName?: string | null, inviterDisplayName?: string | null, inviterUserId?: string | null, joinRule?: string | null, communityServiceDisplayName?: string | null, };

export type PendingInvitationMetadata = { handle: string, roomOrAlias: string | null, via: Array<string>, service: string | null, admissionService: string | null, communityName?: string | null, inviterDisplayName?: string | null, inviterUserId?: string | null, joinRule?: string | null, communityServiceDisplayName?: string | null, storedAt: number, expiresAt: number, };

export type IdentityDto = { publicKey: string, displayName: string, avatarColor: string, };

export type CommunityDto = { id: string, name: string, description: string, memberCount: number, role: "owner" | "admin" | "member", joinedAt: string | null, };

export type ChannelDto = { id: string, communityId: string, name: string, channelType: "text" | "voice", unreadCount: number, };

export type AttachmentThumbnailDto = { fileHash: string, size: number, width: number, height: number, contentType: string, };

export type AttachmentDto = { fileHash: string, filename: string, size: number, chunks: number, sourcePeerId: string, contentType?: string | null,
/**
 * Bounded display metadata for a protected inline preview. Encryption
 * keys, IVs, and media locations remain Rust-only.
 */
thumbnail?: AttachmentThumbnailDto | null, };

export type UndecryptableMessageReason = "sent-before-device" | "keys-not-shared" | "waiting-for-keys" | "could-not-decrypt";

export type UndecryptableMessageDto = { eventId: string, sender: string, originServerTs: number, reason: UndecryptableMessageReason, };

export type MessageDto = { id: string, channelId: string, authorPublicKey: string, authorDisplayName: string, authorAvatarColor: string, content: string, attachments: Array<AttachmentDto>, reactions: Record<string, string[]>, timestamp: string, signature: string, editedAt?: string | null, deletedAt?: string | null, replyToId?: string | null,
/**
 * Matrix thread root event for replies sent with `rel_type: m.thread`.
 * Ordinary replies leave this empty and continue using `reply_to_id`.
 */
threadRootId?: string | null,
/**
 * SDK transaction ID used to reconcile a durable local echo with the
 * eventual server event. This is internal delivery metadata.
 */
transactionId?: string | null,
/**
 * Renderer request ID retained inside the encrypted event so a lost IPC
 * response can be retried without publishing a duplicate.
 */
clientRequestId?: string | null,
/**
 * Delivery status: "sent", "pending", or "failed". None = sent.
 */
deliveryStatus?: "sent" | "pending" | "failed" | null,
/**
 * Present only when Matrix received an event but the SDK could not
 * decrypt its message content.
 */
undecryptable?: UndecryptableMessageDto | null, };

export type DmConversationDto = { id: string, peerPublicKey: string, peerDisplayName: string, peerAvatarColor: string, lastMessageAt: string | null, unreadCount: number, createdAt: string, };

export type DmRequestDto = { roomId: string, inviterUserId: string, inviterDisplayName: string, inviterAvatarColor: string, canAccept: boolean, };

export type BlockedAccountDto = { userId: string, };

export type BlockedAccountPageDto = { accounts: Array<BlockedAccountDto>, nextCursor: string | null, };

export type ReadReceiptDto = { userId: string, displayName: string, };

export type DirectMessageDto = { id: string, conversationId: string, authorPublicKey: string, authorDisplayName: string, authorAvatarColor: string, content: string, timestamp: string, signature: string, attachments: Array<AttachmentDto>, reactions: Record<string, string[]>, seenBy?: Array<ReadReceiptDto> | null, editedAt?: string | null, deletedAt?: string | null, replyToId?: string | null, threadRootId?: string | null, deliveryStatus?: "sent" | "pending" | "failed" | null, };

export type PeerDto = { publicKey: string, displayName: string, avatarColor: string, peerId: string, latency: number, };

export type NetworkStatusDto = { connected: boolean, peerCount: number, averageLatency: number, usingRelay: boolean, };
